### ISSUE TITLE
Angelegte Profile sind nach re-install weg.

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex_markitup#14]
Damit funktionieren die meisten textareas nicht mehr als Editoren.

**Comment by phoebusryan** [comment]
Ja, das ist richtig und logisch. Wenn das Ding mal richtig stabil ist, sind Neuinstallationen ja auch nicht mehr nötig und das Problem hier kommt nicht mehr vor. Aktuell während der Entwicklungs- und Fehlerphase kann so etwas aber vorkommen.

**Comment by tbaddade** [comment]
Sehe ich ein wenig anders. Ich würde auf das DROP verzichten. Daher der Vorschlag, dass die angelegten Profile in den Dataordner landen und danach automatisch wieder in die DB aufgenommen werden.

**Comment by tbaddade** [comment]
Und schon wieder sind alle Profile weg. Ein halte die AddOns immer aktuell, daher kann es schon vorkommen das in einem älteren Projekt ein Update und damit auch ein re-install notwendig wird. Damit sind die Profile dann verschwunden.

**Comment by phoebusryan** [comment]
Ja ich hatte gestern auch so ein Fall. Das 'Feature' wird also sicher kommen und demnächst eingebaut werden.

**Comment by interweave-media** [comment]
nicht nur sind neu angelegte Profile nach Backup weg, neu angelegte Profile schlagen gar nicht erst mehr durch, das heißt, der Editor ist keiner mehr wenn ich ihm ein individuelles Profile zuweise. Den Fall hatte ich NACH Aktualisierung und re-install auf die derzeit aktuelle Version 1.2.1 (gilt für textile und markdown)

**Comment by phoebusryan** [comment]
Beim individuellen Profil musst du im Input das Attribut "class" anpassen. Damit sollte es dann gehen.

Bzgl. den angelegten Profilen sichern, bin ich noch an einer Lösung dran, damit ich z.B. auch die DB Struktur ändern kann und die Daten trotzdem nicht verloren gehen. Aber ich bin dran.

**Comment by interweave-media** [comment]
"class" habe ich natürlich angepasst gehabt: es kommt dann aber ein textarea ohne editor-icon-header. Mir schien das als Feedback wichtig, da du ja an der Sache dran bist.

**Comment by phoebusryan** [comment]
kannst du mir sagen wie du das Profil genannt hast und wie die klasse dann hies? dann würde ich der Sache gleich nachgehen. Evtl. ist da ja wirklich noch ein Fehler drin.

**Comment by interweave-media** [comment]
klar, gerne:
Profile:  "textile_jw"
class: "markitupEditor-textile_jw"

**Comment by phoebusryan** [comment]
Das habe ich gerade probiert. Bei mir klappt es. Hast du Buttons angegeben? Was für welche? Nutzt du die neuste Version?

**Comment by interweave-media** [comment]
Hast du Buttons angegeben?
==> ja, alle (ist quasi eine Kopie von _full
Was für welche?
==> s.o.
Nutzt du die neuste Version?
==> 1.2.1, heute aktualisiert
Kommen Javascriptfehler?
==> no
Hast du mal re-installiert? :-)
==> yes

ich teste das aber auch nochmal. Will hier natürlich keine Verwirrung stiften ;-)

**Comment by phoebusryan** [comment]
@tbaddade Wie würdest du das lösen? In der uninstall.php ein JSON erstellen mit den Profilen und beim installieren schauen ob es ein JSON gibt und dieses am Ende der Installation einlesen?

Was wird eigentlich zuerst ausgeführt; die uninstall.php oder die uninstall.sql?

**Comment by tbaddade** [comment]
Ich würde das DROP aus deiner install.sql löschen und den Aufbau eher so lösen https://github.com/yakamara/redaxo_yrewrite/blob/master/install.php
Hier siehst du auch ein Bsp. für `ALTER TABLE`

> Was wird eigentlich zuerst ausgeführt

Reihenfolge ist immer erst die php-Datei dann die sql-Datei.

> die uninstall.php oder die uninstall.sql?

Die werden bei einem re-install nicht berücksichtigt. Daher könntest du die Profile ggf. im Data-Ordner zwischen speichern (in der install.php).

**Comment by phoebusryan** [comment]
Die Assets werden bei jedem Update kopiert, sodass ein reinstall nicht mehr nötig ist. SQL-Anpassungen werden nun über die update.php gelöst. Daher schliesse ich dies nun.
