### ISSUE TITLE
Preview Funktion

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/rex_markitup#18]
Lässt sich die Preview-Funktion aktivieren?

**Comment by phoebusryan** [comment]
Dies ist schwierig zu bewerkstelligen. Es ist nicht einfach ein 'aktivieren'. Ich weiss, dass es die Möglichkeit im markItUp grundsätzlich gibt, jedoch müsste man das ja so dynamisch bauen, dass CSS-Files, die im Frontend eingebaut sind, automatisch auch im Backend eingebunden werden im Previewwindow. Anderenfalls hätte man ja eine reine, geparsete Vorschau. Du darfst mich aber gerne vom Gegenteil überzeugen und einen PR senden :-)

Ausserdem habe ich neben diesem Editor noch den WYSIWYG-Editor Redactor für Redaxo 5 entwickelt. Damit hätte man natürlich immer direkt eine Vorschau.

Übrigens ist seit grade Version 1.3.0 des AddOns draussen. Darin sind auch Output-Parser enthalten.

**Comment by VIEWSION** [comment]
Danke für das schnelle Feedback. Ich finde das muss gar nicht mit dem Frontend-CSS gekoppelt werden. In den meisten Fällen würde das auch nicht wirklich Sinn machen. Ein Basic-Styling, das man sich ggf. etwas an das Frontend-Design anpassen kann, würde völlig ausreichen.  Wo lässt sich den die Funktion aktivieren?

**Comment by phoebusryan** [comment]
Wie gesagt; es ist nicht einfach ein aktivieren. Ich weiss aber, dass es machbar ist. Siehe hier: http://markitup.jaysalvat.com/examples/textile/ (grüner Haken im Editor)

Wenn man die Frontendstyles aussen vor lässt und stattdessen die Styles vom Backend von Redaxo 5 nimmt, könnte man dies vermutlich relativ einfach umsetzen. Trotzdem benötigt es etwas Zeit. Ich kann mich bei Gelegenheit ja mal einlesen. :-)

**Comment by VIEWSION** [comment]
Alles klar.... ist ja nicht solo wichtig - aber wäre ein schönes feature... Danke!

**Comment by phoebusryan** [comment]
Ist da noch Interesse da?
