### ISSUE TITLE
link insert

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/rex_markitup#32]
es lässt sich kein link einsetzen, sobald das markierte wort nicht mehr im viewport liegt.

**Comment by isospin** [comment]
bei mir taucht das problem in der version 2.0 nicht mehr auf.
die textarea hat ja jetzt eine scrollbar, so das der fall nicht mehr auftritt.

**Comment by phoebusryan** [comment]
Danke fürs Update. In dem Fall schliesse ich hier.
