### ISSUE TITLE
Dateilink wird falsch ersetzt

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/rex_markitup#36]
Beim Setzen eines Dateilinks ist die Ersetzung noch durcheinander.
Im Moment kommt das hier raus:
```
"bild.jpg":/media/bild.jpgDateilink
```

Richtig wäre aber:
```
"Dateilink":/media/bild.jpg
```

**Comment by phoebusryan** [comment]
Danke, fixe ich im nächsten Update
