### ISSUE TITLE
Separatoren

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex_markitup#41]
ggf. via Pipenotation
`heading3,heading4,|,bold,|,orderedlist,unorderedlist,|`

**Comment by phoebusryan** [comment]
Hab ich direkt gebaut und ist in der nächsten Version drin. Bis dahin gibts folgenden Fix:
https://github.com/FriendsOfREDAXO/rex_markitup/commit/042c3d69b9c6fc48bbfefd8c8db23fc1c321874c
