### ISSUE TITLE
Update auf 2.1.0 funktioniert nicht, wenn textile installiert ist.

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex_markitup#42]
```
AddOn "rex_markitup" konnte aus folgendem Grund nicht aktualisiert werden:
Es kann nicht gemeinsam mit dem AddOn textile aktiviert sein!
```

Ich habe die Version 2.0.0 und wollte gerade aktualisieren. Wenn das obige ein Kriterium bleibt, dann sollte m.E. die Version 2.1.0 in 3.0.0 geändert werden.

**Comment by phoebusryan** [comment]
Das kam per PR von @gharlan rein. Er möchte damit ja Textile rauskicken, weils einfach nicht beides braucht. Abgesehen davon, dass beide dieselbe Parser-Library benutzen, gibts aber nach wie vor keine Inkompatibilitäten.

Ob ein BC-Release dafür notwendig ist, weiss ich nicht. Einerseits ja, andererseits nein. Ich starte mal eine Diskussion.

**Comment by gharlan** [comment]
Abhängigkeiten ändern ist laut semver kein BC-Break, somit ist mMn keine 3.0 notwendig.
Man macht ja nicht ein Update, und dann geht plötzlich etwas nicht mehr, sondern wird auf den Konflikt vorher hingewiesen.

Auch wenn es zurzeit keine wirklichen Inkompatibilitäten gibt zwischen den Addons, wollte ich mit der Maßnahme frühzeitig verhindern, dass beide gleichzeitig installiert sind, denn es ist nicht unwahrscheinlich, dass es zukünftig Inkompatibilitäten geben wird aufgrund unterschiedlicher Parser-Versionen. (https://github.com/FriendsOfREDAXO/rex_markitup/pull/40)
Es ist/war aber auch nur ein Vorschlag, kann auch ganz rückgängig gemacht werden, falls ihr das blöd findet.

**Comment by tbaddade** [comment]
Für ein aktuelles Projekt wäre das Aktualisieren via Installer jetzt erst einmal vorbei. Ich ziehe mir das direkt von redaxo.org und passe mir die yml entsprechend an.
