### ISSUE TITLE
Parse Methode - rex_textile::parse

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex_markitup#44]
Da man seit 2.1.0 Textile nicht mehr nebenbei laufen lassen kann, wäre der Methodenaufruf frei und könnte in das AddOn aufgenommen werden

`rex_textile::parse('REX_VALUE[id=1 output=html]');`

**Comment by phoebusryan** [comment]
#42

**Comment by tbaddade** [comment]
> Was stört dich am aktuellen?

Zu lang und man müsste die eigene lib überall anpassen :)

Mir geht es nicht um das Ersetzen der bisherigen Methode sondern um Abwärtskompatibel zu bleiben.

**Comment by schuer** [comment]
Abwärtskompatibilität wäre cool. Aktuell fliegen hier ständig Dinge um die Ohren, weil der Wechsel zwischen Textile und Markitup manuelle Anpassungen erforderlich macht.

**Comment by phoebusryan** [comment]
Abwärtskompatibilität - hm; ich hab nie gesagt, dass textile installiert sein muss. Die Parser sind schon fast ewig dabei.

Ich könnte grundsätzlich die obige Methode zusätzlich einbauen aber so richtig happy wäre ich nicht damit.

**Comment by tbaddade** [comment]
> Aktuell fliegen hier ständig Dinge um die Ohren, weil der Wechsel zwischen Textile und Markitup manuelle Anpassungen erforderlich macht.

Das passiert auch ohne abwärts kompatibel zu sein. Allein durch das Wechseln der AddOns dürfte man an einigen Stellen den Code anpassen.
