### ISSUE TITLE
Link einfügen > Abbrechen Button > Textile Markup landet im Text

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex_markitup#46]

**Comment by phoebusryan** [comment]
Welche Art von Links ist das?

**Comment by tbaddade** [comment]
> Welche Art von Links ist das?

Klick in ein Textfeld ohne Text zu markieren und wähle "externer Link". Beim Prompt klickst du auf abbrechen und es landet das `"":` im Textfeld

**Comment by phoebusryan** [comment]
Das ganze kommt mir bekannt vor, habe ich aber irgendwann mal gefixt. Welche Version nutzt du?

**Comment by tbaddade** [comment]
> Welche Version nutzt du?
2.1.2
