### ISSUE TITLE
Tags in der Ausgabe entfernen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/rex_markitup#49]
Gibt es eine Möglichkeit die Tags (* / _ / href kram usw...)  bei einer Ausgabe zu entfernen?
Nützlich z.B. wenn man den Inhalt auch in einem Titel Tag verwendet.

**Comment by phoebusryan** [comment]
Was ist der Sinn davon? In einem Titel musst du ja kein WYSIWYG oder WYMIWYM-Editor benutzen...?

**Comment by eaCe** [comment]
In diesem Fall benutze ich markitup in einer YForm, diese Ausgabe findet dann auf einer extra Seite statt, wird aber auch auf einer Übersichtsseite für einen gekürzten Intro-Text benutzt. Und im Titel weniger, in dem Fall ist es eben ein normaler Text. Weiter nutze ich das auch für ICAL Einträge und auch dort wäre es störend. Muss ja nicht, ist ja nur eine Anregung / Frage :)

**Comment by tbaddade** [comment]
Wenn das der Parser von sich aus nicht mitbringt, würde ich das nicht weiter verfolgen. Das ist nämlich gar nicht so einfach umzusetzen. Das einfachste für dich @eaCe wäre, den Text zu parsen und dann ein `strip_tags` laufen zu lassen.

**Comment by eaCe** [comment]
Alles klar, dann mache ich das so, danke @tbaddade
