### ISSUE TITLE
Warum inkompatibel mit textile / rex_textile ?

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/rex_markitup#52]
Die aktuelle Version meckert beim installieren / aktivieren wenn Textile aktiv ist. Warum? Ich würde gerne beides verwenden... Ich habe Module wo ich keinen Editor brauche, aber Textile nutzen möchte... auch als Fallback... 

Übrigens - man kann Textile problemlos nach rex_markitup wieder aktivieren... scheint auch zu funktionieren...

**Comment by skerbis** [comment]
Textile ist doch Bestandteil von rex_markitup. Textile wird nicht mehr benötigt.

**Comment by VIEWSION** [comment]
Für Module die explizit rex_markitup mag das sein - nur passiert dann das mit anderen Modulen die die "normale" Textile Implementierung haben:

`Class 'rex_textile' not found`

**Comment by skerbis** [comment]
können ja nicht so viele Module sein, wenn ich mich mal so im Downloadbereich umschaue

**Comment by VIEWSION** [comment]
Sind alles eigene Module... und ich will die Module nicht alle anpassen, die auf diversen Seiten im Einsatz habe, nur wenn ein neues Modul mit rex_markitup kommt. Wie gesagt... es funktioniert ja wenn man Textile nachträglich wieder aktiviert. Ist die Klasse halt doppelt da... nicht schön, aber funktioniert zumindest.

Ich verstehe nur nicht warum man das nicht kompatibel machen kann... Eigentlich sollte rex_markitup textile voraussetzen (wenn man die Kombi nutzen möchte) und nicht umgekehrt... Textile ist ja immerhin ein Core-Addon...

**Comment by tbaddade** [comment]
@VIEWSION Hier siehst du meine Lösung https://gist.github.com/tbaddade/3a2ce01bf6a15feb46a17764f047dde8

**Comment by VIEWSION** [comment]
@tbaddade you.. so geht das auch. Bei der Installation wird dann aber auch noch gemeckert. Ich will auch nicht an rex_markitup herumbasteln. War als Anregung gedacht... Ich würde Textile als Bestandteil von rex_markitup rauswerfen und auf die Standard-Implementierung zurückgreifen... oder höchstens als Fallback falls es nicht installiert ist.

**Comment by tbaddade** [comment]
>  Bei der Installation wird dann aber auch noch gemeckert.

Nein wird nicht. Du hast überall denselben Aufruf via `App::convertMarkup()`. Installiert haben musst du aber nur ein AddOn. Entweder `rex_markitup` oder `textile`. Vorteil dieser Variante ist auch, sobald sich beim Addon oder Parser was ändert, brauchst du nur in der Methode die Anpassungen zu machen und nicht bei den Modulen, PHP-Dateiein oder sonst wo.

**Comment by VIEWSION** [comment]
@tbaddade stimmt... setzt aber voraus dass ich überall die Methode implementieren muss und wieder alle Module ändern muss. Ich finde dass ein AddOn mit Core-Features klar kommen muss und nicht umgekehrt...

**Comment by phoebusryan** [comment]
Markitup hat nie Textile benötigt. Es ist daher schlicht ein Implementierungsfehler. Vermutlich kommt dieser daher, dass MarkItUp für Redaxo 4 Textile benötigt hat. Es gibt nun eben mehrere Lösungsmöglichkeiten und Issues dazu:

https://github.com/FriendsOfREDAXO/rex_markitup/issues/44
https://github.com/FriendsOfREDAXO/rex_markitup/pull/40

**Comment by VIEWSION** [comment]
Warum closed? Lösungen sind das für mich beides nicht...  lasst doch einfach rex_textile und verwendet den internen Parser nur on demand... Ich selber komm schon klar damit - war ja nur als Tipp gemeint um es kompatibel zu halten und die Fehlermeldung bei der Installation zu vermeiden.

**Comment by phoebusryan** [comment]
Definiere interner Parser? Textile gehört nicht zum Core. MarkItUp liefert einen eigenen Textile-Parser mit. Warum eine unnötige Abhängigkeit zu einem anderen Addon haben?

**Comment by VIEWSION** [comment]
Ok - nicht Core.... aber eigentlich ein Default-Addon (auch wenn es beim Innstall-Paket nicht mehr dabei ist) https://github.com/redaxo/redaxo/tree/master/redaxo/src/addons ... Es geht ja nicht um Abhängigkeiten, sondern eher darum es kompatibel zu halten. Wenn rex_textile schon da ist gut, wenn nicht, habt ihr den eigenen an Board. Oder einfach beide Parser nebeneinander... ist ja auch nicht so wild. Mich nervt halt nur die Fehlermeldung beim Installieren von MarkItUp... die ist eigentlich unnötig.

**Comment by phoebusryan** [comment]
Textile und MarkItUp parallel beissen sich aber u.U. weil die Parserversion nicht gleich ist. Redaxo lädt dann quasi per Zufall die eine oder andere Version. Um dies zu verhindern, gibts diese Inkompatilität.

**Comment by VIEWSION** [comment]
verstehe... müsste man halt eine Abfrage / Weiche implementieren. Passt schon... vielleicht lässt sich das ja in Zukunft irgendwie eleganter machen. Nur so als Anregung.

**Comment by phoebusryan** [comment]
Man sollte einfach entweder Textile (deprecated) oder MarkItUp nutzen; nicht beides. Und wenn man MarkItUp nutzt, sollte man auch die Ausgabe vom MarkItUp nutzen. Damit gibts dann auch keine Probleme oder Inkompatibilitäten. Das Problem besteht ja nur auf bestehenden Seiten wo Textile noch mitgeliefert wurde. Mittlerweile ist das ja nicht mehr so.
